### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by mxgrn** [gpedic/ex_q#1]
1. Building the q

```elixir
    iex> pipeline = Q.new()
    |> Q.put(:init, %{test: "setup"})
    |> Q.run(:read, fn _ -> {:ok, "Once upon a time ..."} end)
```

How about replacing both `put` and `run` with a single `add`?

2. Result

```elixir
{:ok, %{init: %{test: "setup"}, read: "Once upon a time ..."}}
```

Maybe instead of a map, a keyword list would be more valuable, preserving the sequence of the execution.

**Comment by gpedic** [comment]
> How about replacing both put and run with a single add?

2 points I like about `put,run`

1. it's in line with the API `Ecto.Multi` provides, which was one of my goals
2. I not too fond of mashing together two separate behaviors for what seems to be a small amount of convenience? 
Btw it's possible to `put` anything, including a function reference or mfa tuple since there is no ambiguity, having just `add` would mean that's no longer possible without workarounds

> Maybe instead of a map, a keyword list would be more valuable, preserving the sequence of the execution.

But then pattern matching on the state would become pretty much impossible. Also it is possible to get the order from the q via `Q.to_list(pipeline)`, though I think this also returns the content of the operation, if it's a common case then adding a convenience function to just return the operations might be needed
